### ISSUE TITLE
Performance of inspect in pedantic package very low

### ISSUE THREAD

**Issue by rathaustreppe** [LostInDarkMath/pedantic-python-decorators#24]
Hihi,

I profiled my project & tests with CProfile and found out your pedantic package relies heavily on the inspect package. Which makes your pedantic decorators quite slow.
I added two pictures of the profiling:

It spends two full seconds in the inspect package with a total of 2800 calls! (left side of the graph)
getsource is called by three of your functions: is_property_setter, is_function_that_wants_args and is_static_method.
![project profile](https://user-images.githubusercontent.com/68727256/94047778-de22bf00-fdd2-11ea-8686-ccb37ef132ac.png)

In my ~130 tests, inspect is called 20000(!!) times and spending 15 seconds in there. (bottom the graph)
![tests profile](https://user-images.githubusercontent.com/68727256/94047792-e1b64600-fdd2-11ea-88ff-6f6a1b7c419f.png)

Hope you can add a little memoization in there!

**Comment by LostInDarkMath** [comment]
Thanx bro, I totally forgot to profile my project. I'll call `inspect.getsource()` only once per method and buffer the result. I think this should increase performance.
