### ISSUE TITLE
pedantic fails at operator overload

### ISSUE THREAD

**Issue by rathaustreppe** [LostInDarkMath/pedantic-python-decorators#3]
Hey there,
I have an issue when decorating a function with @pedantic that overloads the python in-operator.
Example:
```python
@pedantic
def __contains__(self, item:str) -> bool:
  if item in self.my_string:
    return True
  else:
    return False
```
I override contains to enable following syntax:
```python
my_text = MyTextObject('abcd')
if 'ab' in my_text -> True # do something
```
But when I decorate contains with @pedantic and call it, then I get the error-message:
```python
assert args_without_self == (), f'Use kwargs when you call {func.__name__}! {args_without_self}'
AssertionError: Use kwargs when you call __contains__! ('ab',)
```
I guess, because the python in-operator doesnt call contains with explicit function arguments? Is it a problem with your implementation or is it Python?

full code snippet:

```python
from pedantic import pedantic
class MyTextObject:
    def __init__(self, text):
        self.my_string = text

    @pedantic
    def __contains__(self, item: str) -> bool:
        if item in self.my_string:
            return True
        else:
            return False

my_text = MyTextObject('abcd')
if 'ab' in my_text:
    print('yes, its working')
```

**Comment by LostInDarkMath** [comment]
Good catch. This is fixed in https://github.com/LostInDarkMath/pedantic-python-decorators/pull/7/commits/41f7f0e698dd2e7bb886da91a21972b3487454b0.
