### ISSUE TITLE
pedantic fails at type hints of custom class inside custom class

### ISSUE THREAD

**Issue by rathaustreppe** [LostInDarkMath/pedantic-python-decorators#4]
Hey there,
I came across a small issue with the typeHint parser.

Consider the class Token has a function to compare itself to another token object:
```python
class Token():
  @pedantic
  def compare(self, other: 'Token') -> bool
    # compares tokens. Returns True if equal, or false otherwise

```
Comparing two tokens:
```python
tok1 = Token('abcd')
tok2 = Token('abcd')
if tok1.compare(other=tok2): # true, do something
```
I get the error message:
```python
  File "...\lib\site-packages\pedantic\type_hint_parser.py", line 14, in is_instance
    if type_.__module__ == 'typing':
AttributeError: 'str' object has no attribute '__module__'
```

If I look inside the type hint parser I see the cause of the error:
```python
if type_.__module__ == 'typing':
```
In this case you want to access the module-attribute of the string 'Token' which of course doesnt work.

It would be nice if you could fix the typehint parser in this special case.

**Comment by LostInDarkMath** [comment]
This is fixed in https://github.com/LostInDarkMath/pedantic-python-decorators/pull/7/commits/6ed373db4a0d3cfb5242a0973559c3b2f2ae2a6c.
