### ISSUE TITLE
Issue with pypi source builds

### ISSUE THREAD

**Issue by mikemhenry** [LostInDarkMath/pedantic-python-decorators#89]
I am working to get this package onto conda-forge, but it looks like there is an issue with the source tarballs uploaded onto pypi. The wheels work fine, but when building from source, it looks like the package itself is missing from the tarballs. 

See:
https://github.com/conda-forge/staged-recipes/pull/23986#issuecomment-1731951756

Thanks!

**Comment by LostInDarkMath** [comment]
Hi Mike,
thanks for your effort to get this to conda-forge :+1: 

I fixed the bug, please try it again with pedantic 1.15.1 and check if it fixed your issue.

**Comment by LostInDarkMath** [comment]
Closing, since https://github.com/conda-forge/staged-recipes/pull/23986 is merged.
